# Generated by Django 4.2.11 on 2026-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatOurClientsSay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='clients/profile/')),
                ('box_image', models.ImageField(upload_to='clients/box/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
