# Generated by Django 4.2.11 on 2026-05-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0002_whatourclientssay'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOnOurReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='reels/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'New On Our Reel',
                'verbose_name_plural': 'New On Our Reel',
            },
        ),
    ]
