# Generated by Django 4.2.11 on 2026-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='digital_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Digital Impact Stories',
                'verbose_name_plural': 'Digital Impact Stories',
            },
        ),
    ]
