# Generated by Django 4.2.11 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0005_digitalimpactstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeContentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='creative_portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creative Content Portfolio',
                'verbose_name_plural': 'Creative Content Portfolio',
            },
        ),
    ]
