# Generated by Django 4.2.11 on 2026-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0006_creativecontentportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativecontentportfolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
