# Generated by Django 4.2.11 on 2026-05-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0007_creativecontentportfolio_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreativeContentPortfolio',
        ),
    ]
