# Generated by Django 4.2.11 on 2026-05-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0008_delete_creativecontentportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeContentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
