# Generated by Django 4.2.11 on 2026-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0013_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
