# Generated by Django 4.2.11 on 2026-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0014_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
