# Generated by Django 4.2.11 on 2026-05-06 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0016_readblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readblog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
