# Generated by Django 4.2.11 on 2026-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotoapp', '0017_alter_readblog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalimpactstory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
